apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qa-team-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: qa-team-sa 
  namespace: qa-team
roleRef:
  kind: ClusterRole
  name: qa-team-clusterrole
  apiGroup: rbac.authorization.k8s.io

