stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the application..."

lint-kubeconform:
  stage: test
  image:
    name: ghcr.io/yannh/kubeconform:latest-alpine
    entrypoint: [""]
  script:
  - /kubeconform -summary -output json manifests/

deploy:
    stage: deploy
    dependencies:
      - lint-kubeconform
    script:
     - echo "Deployed to Cluster"