apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: kubermates
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: registry.code.fbi.h-da.de/kubermates/devops-kubernetes/web-app:v1.4
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: web-app-config
              key: APP_ENV
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: web-app-config
              key: LOG_LEVEL
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: web-app-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: web-app-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: web-app-config
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: web-app-secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: web-app-secrets
              key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
      - name: config-volume
        configMap:
          name: web-app-config
      imagePullSecrets:
      - name: regcred
