apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
  namespace: kubermates
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  DATABASE_HOST: "mongodb-service"
  DATABASE_PORT: "27017"
  DATABASE_NAME: "mydb"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kubermates
  name: web-app-secrets
type: Opaque
data:
  MONGO_URI: eW91ci1tb25nby11cmk=
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # base64 encoded 'admin'
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
