apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: kubermates
data:
  init-db.sh: |
    #!/bin/bash

    # MongoDB credentials
    MONGO_INITDB_ROOT_USERNAME=$(cat /etc/mongo-secrets/MONGO_INITDB_ROOT_USERNAME)
    MONGO_INITDB_ROOT_PASSWORD=$(cat /etc/mongo-secrets/MONGO_INITDB_ROOT_PASSWORD)

    # Wait for MongoDB to be ready
    until mongo --host mongodb-service --username "$MONGO_INITDB_ROOT_USERNAME" --password "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase "admin" --eval "print(\"waited for connection\")"
    do
      echo "Waiting for MongoDB to be ready..."
      sleep 5
    done

    # Check if admin user already exists
    USER_EXISTS=$(mongo --host mongodb-service --username "$MONGO_INITDB_ROOT_USERNAME" --password "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase "admin" --eval '
      db.getSiblingDB("admin").getUser("'"$MONGO_INITDB_ROOT_USERNAME"'")' --quiet)

    if [ "$USER_EXISTS" == "null" ]; then
      echo "Creating admin user..."
      mongo --host mongodb-service --username "$MONGO_INITDB_ROOT_USERNAME" --password "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase "admin" --eval '
        db.createUser({
          user: "'"$MONGO_INITDB_ROOT_USERNAME"'",
          pwd: "'"$MONGO_INITDB_ROOT_PASSWORD"'",
          roles: [{ role: "root", db: "admin" }]
        });
      '
    else
      echo "Admin user already exists, skipping creation."
    fi
