apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-snapshot
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/snapshots
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-snapshot
  namespace: kubermates
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

