# Service Accounts
apiVersion: v1
kind: ServiceAccount
metadata:
  name: visitor-sa
  namespace: kubermates
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-team-sa
  namespace: kubermates
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-team-sa
  namespace: kubermates

# Roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubermates
  name: visitor-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubermates
  name: test-team-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kubermates
  name: dev-team-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["*"]

# RoleBindings
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: visitor-rolebinding
  namespace: kubermates
subjects:
- kind: ServiceAccount
  name: visitor-sa
  namespace: kubermates
roleRef:
  kind: Role
  name: visitor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-team-rolebinding
  namespace: kubermates
subjects:
- kind: ServiceAccount
  name: test-team-sa
  namespace: kubermates
roleRef:
  kind: Role
  name: test-team-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-rolebinding
  namespace: kubermates
subjects:
- kind: ServiceAccount
  name: dev-team-sa
  namespace: kubermates
roleRef:
  kind: Role
  name: dev-team-role
  apiGroup: rbac.authorization.k8s.io
