apiVersion: v1
kind: Service
metadata:
  namespace: kubermates
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080  # You can specify a port within the range 30000-32767, or omit this line to have one assigned automatically
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - port: 27017
  clusterIP: None
  selector:
    app: mongodb

