apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: host-volume
          mountPath: /etc/data
          readOnly: true
  volumes:
    - name: host-volume
      hostPath:
        path: /mnt/data
        type: Directory
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
