apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  restartPolicy: Never
  volumes:
    - name: shared-storage
      emptyDir: {}

  containers:
  - name: nginx-container-1
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - name: shared-storage
        mountPath: /usr/share/nginx/html

  - name: nginx-container-2
    image: nginx
    ports:
    - containerPort: 81
    volumeMounts:
    - name: shared-storage
      mountPath: /etc/nginx/conf.d


