apiVersion: v1
kind: Service
metadata:
  namespace: kubermates
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: webapp-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
