apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-deployment
  namespace: kubermates
spec:
  selector:
    matchLabels:
      app: secrets-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: secrets-deployment
    spec:
      containers:
      - name: alpine-container
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo '##### Secrets #####'; cd /etc/appsecrets && echo username && cat username && echo -e '\n'password && cat password && echo -e '\n' ; sleep 60; done"]
        volumeMounts:
        - name: alpine-volume
          mountPath: /etc/appsecrets
          readOnly: true
      volumes:
      - name: alpine-volume
        secret:
          secretName: appsecrets
