apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-configmap
  namespace: kubermates
data:
  index.php: |
    <?php
    session_start();
    if (!isset($_SESSION['count'])) {
      $_SESSION['count'] = 0;
    }
    $_SESSION['count']++;
    ?>
    <!DOCTYPE html>
    <html>
    <head>
      <title>DevOpsK8s</title>
      <style>
        body {
          background-color: #333333;
          color: #FFFFFF;
          text-align: center;
          padding-top: 100px;
          font-size: 24px;
          font-family: Arial, sans-serif;
        }
      </style>
    </head>
    <body onload="showTime()">
      <h1>Welcome to the DevOpsK8s website!</h1>
      <p>This page has been visited <?php echo $_SESSION['count'];?> times. </p>
      <p>Your IP Address is:  <?php echo $_SERVER['REMOTE_ADDR'];?> </p>
      <p>Time & Date of your request was: <span id="datetime"></span> </p>
      <br><br><br><br><br>
      <script>document.getElementById("datetime").innerHTML = Date(Date.now())</script>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: kubermates
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;

        index index.php index.html index.htm;
        error_log /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: kubermates
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-deployment
  template:
    metadata:
      labels:
        app: webapp-deployment
    spec:
      containers:
      - name: webapp-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webapp-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      - name: php-container
        image: php:fpm-alpine
        volumeMounts:
        - name: webapp-volume
          mountPath: /usr/share/nginx/html
      - name: alpine-container
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo $STAGE: $MESSAGE; sleep 30; done"]
        env:
        - name: MESSAGE
          valueFrom: 
            configMapKeyRef:
              name: env-configmap
              key: message
        - name: STAGE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: stage
        volumeMounts:
        - name: alpine-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: webapp-volume
        configMap:
          name: webapp-configmap
      - name: nginx-volume
        configMap:
          name: nginx-configmap
      - name: alpine-volume
        configMap: 
          name: env-configmap
