apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: test-team-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:latest
        ports:
        - containerPort: 80

