apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-team-rolebinding
  namespace: test-team
subjects:
- kind: ServiceAccount
  name: test-team-sa
  namespace: test-team
roleRef:
  kind: Role
  name: test-team-role
  apiGroup: rbac.authorization.k8s.io

